# Generated by Django 3.1.2 on 2020-10-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201016_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
